server:
  port: 8011

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: member-service
  profiles:
    active: local
  #  config:
  #    import: optional:configserver:http://localhost:8888

  datasource:
    url: jdbc:mysql://150.230.253.90:3306/giunne_member_db?useUnicode=true&serverTimezone=Asia/Seoul&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
    username: jyj1143
    password: 1q2w3e4r!
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
      port: 6379
      host: 127.0.0.1 # 레디스 서버 호스트

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        jdbc:
          batch_size: 100
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
    show-sql: true



  servlet:
    multipart:
      max-file-size: 50MB # 파일 업로드 요청 시 하나의 파일 크기를 50MB 제한
      max-request-size: 100MB # 파일 업로드 요청 시 모든 파일 크기합을 100MB 제한

# swagger
springdoc:
  api-docs:
    version: openapi_3_1
    enabled: true
    path: /api/member/v3/api-docs
  enable-spring-security: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

token:
  issuer: giunne
  secret: 9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9asdfas # 임의의 문자열
  access-token-expiration-time: 900000  # 15분 1000(ms) x 60(s) x 15(m)
  refresh-token-expiration-time: 1209600000 # 2주 1000(ms) x 60 (s) x 60(m) x 24(h) x 14(d)

app:
  apiUrl:
    member-service: http://localhost:9001/v1/api/member
    item-service: http://localhost:9001/v1/api/items
    quest-service: http://localhost:9001/v1/api/quest
    community-service: http://localhost:9001/v1/api/community




