package com.giunne.memberservice.domain.school.domain.constant;

public enum SchulKndScCode {

    SPECIAL_SCHOOL("1"),
    HIGH_SCHOOL("2"),
    MIDDLE_SCHOOL("3"),
    ELEMENTARY_SCHOOL("4"),

    COMMUNICATIONS_HIGH_SCHOOL("11"),
    COMMUNICATIONS_MIDDLE_SCHOOL("12"),

    LIFELONG_SCHOOL_HIGH_3_6_SEMESTERS("21"),
    LIFELONG_SCHOOL_HIGH_2_6_SEMESTERS("22"),
    LIFELONG_SCHOOL_MIDDLE_3_6_SEMESTERS("23"),
    LIFELONG_SCHOOL_MIDDLE_2_6_SEMESTERS("24"),
    LIFELONG_SCHOOL_ELEMENTARY_4_12_SEMESTERS("25"),
    LIFELONG_SCHOOL_ELEMENTARY_3_6_SEMESTERS("26"),

    VARIOUS_SCHOOLS_FOREIGN_SCHOOLS("31"),
    VARIOUS_SCHOOLS_ALTERNATIVE_SCHOOLS("32"),
    VARIOUS_HIGH_SCHOOLS("34"),
    VARIOUS_MIDDLE_SCHOOLS("35"),
    VARIOUS_SCHOOLS_ELEMENTARY("36"),

    CITIZENS_HIGH_SCHOOL("41"),
    HIGH_TECH_SCHOOL("42"),
    JOINT_LABORATORY("43"),

    INTERNATIONAL_SCHOOL("44"), //
    FOREIGN_SCHOOL("45"), //
    OVERSEAS_KOREAN_SCHOOL_HIGH_SCHOOL("46"), //
    OVERSEAS_KOREAN_SCHOOL_MIDDLE("47"), //
    OVERSEAS_KOREAN_SCHOOL_ELEMENTARY("48"); //

    private final String code;


    SchulKndScCode(String code) {
        this.code = code;
    }


}
